name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        ports:
          - 2376:2376
        env:
          DOCKER_HOST: tcp://docker:2376
          DOCKER_TLS_VERIFY: '1'
        options: --privileged

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: cfontelar22/fontelar_christma_coding_assignment12
