name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
              node-version: '20.10.0'
              npm-version: '10.2.3'


      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test # Ensure your package.json has a test script that runs Jest

      - name: Run Tests with Coverage (optional)
        run: npm test -- --coverage # This is optional if you want to collect coverage
